// ─── Lead & Contact ───────────────────────────────────────────────────────────
export interface LeadRecord {
  id: string;
  name: string;
  phone: string;
  email: string;
  createdAt: string;
}

// ─── Conversation State Machine ───────────────────────────────────────────────
export type ConversationStage =
  | 'greeting'
  | 'confirm_name'
  | 'ask_location'
  | 'ask_property_type'
  | 'ask_topology'
  | 'ask_budget'
  | 'ask_consent'
  | 'property_search'
  | 'final_response'
  | 'completed';

export type PropertyType = 'residential' | 'commercial' | null;
export type ResidentialTopology = '1BHK' | '2BHK' | '3BHK' | '4BHK' | null;
export type CommercialSubtype = 'Shop' | 'Office' | 'Plot' | null;

export interface CollectedData {
  confirmedName: string | null;
  location: string | null;
  propertyType: PropertyType;
  residentialTopology: ResidentialTopology;
  commercialSubtype: CommercialSubtype;
  budgetRaw: string | null;
  budgetMin: number | null;
  budgetMax: number | null;
  consent: boolean | null;
  propertyCount: number | null;
}

// ─── Chat Messages ────────────────────────────────────────────────────────────
export interface ChatMessage {
  id: string;
  role: 'agent' | 'user' | 'system';
  content: string;
  timestamp: string;
  stage?: ConversationStage;
  isLLM?: boolean; // true if generated by Groq, false if scripted fallback
}

// ─── Qualification ────────────────────────────────────────────────────────────
export type QualificationDecision = 'Qualified' | 'Not Qualified';

export interface QualificationReason {
  criterion: string;
  passed: boolean;
  detail: string;
}

export interface QualificationSummary {
  leadId: string;
  decision: QualificationDecision;
  reasons: QualificationReason[];
  collectedData: CollectedData;
  propertyCount: number;
  score: number;
  maxScore: number;
  timestamp: string;
}

/**
 * THE CANONICAL FINAL OUTPUT FORMAT
 * This is the exact JSON required by the assignment spec.
 */
export interface FinalQualificationOutput {
  contact_name: string;
  location: string;
  property_type: string;
  subtype: string;
  budget: string;
  consent: string;     // "Yes" | "No" | "Not provided"
  property_count: number;
  qualification: 'Qualified' | 'Not Qualified';
  reason: string;
}

// ─── Session ──────────────────────────────────────────────────────────────────
export interface ConversationSession {
  id: string;
  lead: LeadRecord;
  stage: ConversationStage;
  collectedData: CollectedData;
  messages: ChatMessage[];
  qualification: QualificationSummary | null;
  finalOutput: FinalQualificationOutput | null; // required output format
  startedAt: string;
  completedAt: string | null;
  stageAttempts: Record<string, number>; // tracks retry count per stage
}

// ─── Property Search ──────────────────────────────────────────────────────────
export interface PropertySearchParams {
  location: string;
  propertyType: PropertyType;
  topology: ResidentialTopology | CommercialSubtype;
  budgetMin: number | null;
  budgetMax: number | null;
}

export interface PropertySearchResult {
  count: number;
  source: string;
  query: PropertySearchParams;
  timestamp: string;
}

// ─── App State ────────────────────────────────────────────────────────────────
export type AppView = 'form' | 'chat' | 'summary' | 'logs';
